#pragma config(Motor,  port2,           LeftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DoorMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//turn the door motoe to rotate the door and allow the ball to drop
	motor[DoorMotor] = 15;
	wait1Msec(500);
	motor[DoorMotor] = 0;
	//stop motors again to let ball settle
	motor[RightMotor] = 0;
	motor[LeftMotor] = 0;
	wait1Msec(1000);
	//drive back away from platform
	motor[RightMotor] = -50;
	motor[LeftMotor] = 50;
	wait1Msec(400);
	//close drop down door
	motor[DoorMotor] = -25;
	wait1Msec(400);
	//stop everything
	stopAllTasks();
}
