#pragma config(Sensor, dgtl1,  Button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  Button2,        sensorTouch)
#pragma config(Motor,  port2,           LeftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DoorMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// testing movement with button presets
task main()
{
	while (1) { //keep repeating this cycle forever because 1 is always true
		motor[LeftMotor] = 0; //start with the motor not moving
		motor[RightMotor] = 0; //start with the motor not moving
		// *(one of the motors was inverted so had to run in the negatives)
		// this button has the robot driving straigt for 3 meters
		if(SensorValue[Button1] != 0){ //if the sensor outputs any value(if it is pressed)
			motor[LeftMotor] = -80; //have the motor running at -80 power
			motor[RightMotor] = 127; //have the motor running at 127 power
			wait1Msec(1400);//this causes a turn rotation for 1000ms
		}
		// this button tests the robots ability to turn
		if(SensorValue[Button2] != 0){ //if the sensor outputs any value(if it is pressed)
			motor[RightMotor] = 100; //have the motor running at 127 power
	    		motor[LeftMotor] = 100; //have the motor running at -127 power
			wait1Msec(425);//this causes a turn rotation for 425ms (90 degree turn)
		}
	}
}
